name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
env:
  OKTETO_SERVER: ${{ secrets.OKTETO_SERVER }}
  OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s

      - name: Login in dockerhub
        uses: docker/login-action@v2
        with:
          username: andryushabolkonskiy
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build docker images
        run: |
          docker build ./src/bonus-service/ -t andryushabolkonskiy/rsoi-lab4:bonus
          docker build ./src/flight-service/ -t andryushabolkonskiy/rsoi-lab4:flight
          docker build ./src/gateway-service/ -t andryushabolkonskiy/rsoi-lab4:gateway
          docker build ./src/ticket-service/ -t andryushabolkonskiy/rsoi-lab4:ticket

      - name: Push docker images
        run: |
          docker push andryushabolkonskiy/rsoi-lab4:bonus
          docker push andryushabolkonskiy/rsoi-lab4:flight
          docker push andryushabolkonskiy/rsoi-lab4:ticket
          docker push andryushabolkonskiy/rsoi-lab4:gateway

      - name: Deploy to Okteto
        run: |
          kubectl config set-cluster flight-service-cluster --server="$OKTETO_SERVER" --insecure-skip-tls-verify=true
          kubectl config set-credentials cloud_okteto_com-user --token="$OKTETO_TOKEN"
          kubectl config set-context default --cluster=flight-service-cluster --user=cloud_okteto_com-user --namespace="andryushabolkonskiy"
          kubectl config use-context default
          cd k8s && helm delete services && helm install services ./services-chart
          sleep 60

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"